config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, param: :tag do
    resources :users, only: %i[index new create], controller: 'users'
    resources :posts, only: [:index], controller: 'posts'
  end

  resources :users, param: :pseudonym do
    resources :posts, controller: 'posts'
  end

  resources :posts, param: :slug

  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'sign_up' => 'users#new', as: 'sign_up'

  resources :sessions

  root 'posts#index'
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Timestamps

  paginates_per 10

  # :reek:Attribute
  attr_accessor :password, :password_confirmation

  protected

  field :pseudonym, type: String
  field :name, type: String
  field :email, type: String
  field :passhash, type: String
  field :passsalt, type: String

  belongs_to :company, dependent: :nullify, index: true

  validates :password, confirmation: true
  validates :password, presence: { on: :create }
  validates :pseudonym, :email, uniqueness: true
  validates :pseudonym, :name, :email, presence: true

  before_create :encrypt_password

  set_callback(:create, :before) do |_doc|
    encrypt_password
  end

  def encrypt_password
    return if password.blank?

    self.passsalt = BCrypt::Engine.generate_salt
    self.passhash = BCrypt::Engine.hash_secret(password, passsalt)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# :reek:InstanceVariableAssumption
class UsersController < ApplicationController
  include ApplicationHelper

  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    page_num = params[:page]
    @users = User.where(deleted_at: nil).page page_num
    @users_archive = User.where(:deleted_at.ne => nil).page page_num
  end

  # GET /users/:pseudonym
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/:pseudonym/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(create_params)

    if @user.save
      # redirect_to root_url, :notice => "Signed up!"
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/:pseudonym
  def update
    return unless access_by_user_id(@user._id)

    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/:pseudonym
  def destroy
    return unless access_by_user_id(@user._id)

    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = user(params[:pseudonym])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    # TODO: make separate for each endpoint
    params.require(:user).permit(:pseudonym, :name, :email, :company_id, :password)
  end

  def create_params
    params.require(:user).permit(:pseudonym, :name, :email, :company_id, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.haml
- if @user.errors.any?
  #error_explanation
    %h2 #{pluralize(@user.errors.count, 'error')} prohibited this user from being saved:
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg
.field
  = f.label :email
  = f.text_field :email
.field
  = f.label :name
  = f.text_field :name
- if %w[create new].include?(action_name)
  .field
    = f.label :pseudonym
    = f.text_field :pseudonym
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation
    = f.text_field :password_confirmation
.field
  = f.label :company
  = f.select :company_id, Company.all.collect { |c| [c.title, c.id] }, selected: params[:company_id],
    include_blank: 'безработный'
.actions= f.submit 'Save'

app/views/users/_user.html.haml
%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Company:
  = company_by_id(@user.company_id).title
%hr
- if access_by_user_id(@user._id)
  = link_to 'Edit', edit_user_path(@user.pseudonym)
  |
  - if @user.deleted_at.blank?
    = link_to 'Destroy', user_path(@user.pseudonym), method: :delete, data: { confirm: 'Are you sure?' }
    |

app/views/users/edit.html.haml
- if @user.blank?
  User does not exist or was removed
  %br
- else
  %h1 Editing user
  = form_for @user, url: user_path(@user.pseudonym), method: :put, html: { autocomplete: 'off' } do |f|
    = render 'form', f: f
= link_to 'Back', users_path

app/views/users/index.html.haml
%h2
  Users [
  = link_to @users.count, posts_path
  - if current_user
    = link_to '+', new_user_path
  - else
    +
  - if @users_archive.count.positive?
    = link_to @users_archive.count, users_path(archive: 1)
  - else
    0
  ]
- collection = params[:archive].present? ? @users_archive : @users
- index = (collection.current_page - 1) * collection.default_per_page
- if collection.present?
  %table
    %thead
      %tr
        %th= collection.current_page
        %th @
        %th Name
        %th Employment
        %th Email
        %th
        %th
    %tbody
      - collection.each do |user|
        - item = user.pseudonym
        %tr
          %td= index += 1
          %td= link_to item, user_path(item)
          %td= user.name
          %td= company_by_id(user.company_id).present? ? company_by_id(user.company_id).title : '-'
          %td= user.email
          -# - if current_user
            -# %td= link_to 'Edit', edit_user_path(item)
          -# %td= link_to 'Posts', user_posts_path(item)
  - if params[:archive].present?
    = paginate @users_archive
  - else
    = paginate @users
- else
  Nothing so far...
%br

app/views/users/new.html.haml
%h1 New user
= form_for @user, html: { autocomplete: 'off' } do |f|
  = render 'form', f: f
= link_to 'Back', users_path

app/views/users/show.html.haml
- if @user.blank?
  User does not exist or was removed
  %br
- else
  = render 'user'
= link_to 'Back', users_path