config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, param: :tag do
    resources :users, only: %i[index new create], controller: 'users'
    resources :posts, only: [:index], controller: 'posts'
  end

  resources :users, param: :pseudonym do
    resources :posts, controller: 'posts'
  end

  resources :posts, param: :slug

  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'sign_up' => 'users#new', as: 'sign_up'

  resources :sessions

  root 'posts#index'
end

app/models/company.rb
# frozen_string_literal: true

class Company
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Timestamps

  paginates_per 10

  field :tag, type: String
  field :title, type: String

  has_many :posts, as: :posts, inverse_of: :company, dependent: :nullify
  has_many :users, as: :users, inverse_of: :company, dependent: :nullify

  validates :tag, uniqueness: true
  validates :tag, :title, presence: true
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

# :reek:InstanceVariableAssumption
class CompaniesController < ApplicationController
  include ApplicationHelper

  before_action :set_company, only: %i[show edit update destroy]

  # GET /companies
  def index
    page_num = params[:page]
    @companies = Company.where(deleted_at: nil).page page_num
    @companies_archive = Company.where(:deleted_at.ne => nil).page page_num
  end

  # GET /companies/:tag
  def show; end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/:tag/edit
  def edit; end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to companies_path, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/:tag
  def update
    return unless access_by_user_id(0)

    if @company.update(company_params)
      redirect_to companies_path, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /companies/:tag
  def destroy
    return unless access_by_user_id(0)

    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = company(params[:tag])
  end

  # Only allow a trusted parameter "white list" through.
  def company_params
    params.require(:company).permit(:tag, :title)
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/views/companies/_company.html.haml
%p
  %b Title:
  = @company.title
%hr
- if @user && access_by_user_id(@user._id)
  = link_to 'Edit', edit_company_path(@company.tag)
  |
  = link_to 'Destroy', company_path(@company.tag), method: :delete, data: { confirm: 'Are you sure?' }
  |

app/views/companies/_form.html.haml
- if @company.errors.any?
  #error_explanation
    %h2 #{pluralize(@company.errors.count, 'error')} prohibited this company from being saved:
    %ul
      - @company.errors.full_messages.each do |msg|
        %li= msg
- if %w[create new].include?(action_name)
  .field
    = f.label :tag
    = f.text_field :tag
.field
  = f.label :title
  = f.text_field :title
.actions= f.submit 'Save'

app/views/companies/edit.html.haml
- if @company.blank?
  Company does not exist or was removed
  %br
- else
  %h1 Editing company
  = form_for @company, url: company_path(@company.tag), method: :put do |f|
    = render 'form', f: f
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h2
  Companies [
  = link_to @companies.count, companies_path
  - if access_by_user_id(0)
    = link_to '+', new_company_path
  - else
    +
  - if @companies_archive.count.positive?
    = link_to @companies_archive.count, companies_path(archive: 1)
  - else
    0
  ]
- collection = params[:archive].present? ? @companies_archive : @companies
- index = (collection.current_page - 1) * collection.default_per_page
- if collection.present?
  %table
    %thead
      %tr
        %th= collection.current_page
        %th #
        %th Title
        %th
        %th
        %th
        %th
    %tbody
      - collection.each do |company|
        - item = company.tag
        %tr
          %td= index += 1
          %td= link_to item, company_path(item)
          %td= company.title
          -# - if access_by_user_id(0)
            -# %td= link_to 'Employees', company_users_path(item)
          -# %td= link_to 'Posts', company_posts_path(item)
  - if params[:archive].present?
    = paginate @companies_archive
  - else
    = paginate @companies
- else
  Nothing so far...

app/views/companies/new.html.haml
%h1 New company
= form_for @company do |f|
  = render 'form', f: f
= link_to 'Back', companies_path

app/views/companies/show.html.haml
- if @company.blank?
  Company does not exist or was removed
  %br
- else
  = render 'company'
= link_to 'Back', companies_path