config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, param: :tag do
    resources :users, only: %i[index new create], controller: 'users'
    resources :posts, only: [:index], controller: 'posts'
  end

  resources :users, param: :pseudonym do
    resources :posts, controller: 'posts'
  end

  resources :posts, param: :slug

  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'sign_up' => 'users#new', as: 'sign_up'

  resources :sessions

  root 'posts#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Timestamps

  paginates_per 10

  field :slug, type: String
  field :title, type: String
  field :text, type: String
  field :keyword, type: String

  belongs_to :company, index: true
  belongs_to :user, index: true

  validates :slug, uniqueness: true
  validates :slug, :title, :text, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# :reek:InstanceVariableAssumption
class PostsController < ApplicationController
  include ApplicationHelper

  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  def index
    page_num = params[:page]
    @posts = Post.where(deleted_at: nil).page page_num
    @posts_archive = Post.where(:deleted_at.ne => nil).page page_num
  end

  # GET /posts/:slug
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/:slug/edit
  def edit; end

  # POST /posts
  def create
    original_params = post_params.merge!(company_id: current_user.company_id, user_id: current_user._id)
    @post = Post.new(original_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/:slug
  def update
    return unless access_by_user_id(@post.user_id)

    if @post.update(post_params)
      redirect_to posts_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/:slug
  def destroy
    return unless access_by_user_id(@post.user_id)

    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = post(params[:slug])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:slug, :text, :title, :keyword, :company_id)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.haml
- if @post.errors.any?
  #error_explanation
    %h2 #{pluralize(@post.errors.count, 'error')} prohibited this post from being saved:
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg
- if %w[create new].include?(action_name)
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :title
    = f.text_field :title
.field
  = f.label :text
  = f.text_field :text
.field
  = f.label :keyword
  = f.text_field :keyword
.actions= f.submit 'Save'

app/views/posts/_post.html.haml
- if @post.keyword.present? && params[:keyword] != @post.keyword && current_user&.company_id != @post.company_id
  = form_for @post, url: post_path(@post.slug), method: :get, html: { autocomplete: 'off' } do |f|
    .field
      = f.label :keyword
      = f.text_field :keyword, name: 'keyword'
    .actions= f.submit 'Access post', name: nil
- else
  %p= @post.text
  %hr
  - if access_by_user_id(@post.user_id)
    = link_to 'Edit', edit_post_path(@post.slug)
    |
    - if @post.deleted_at.blank?
      = link_to 'Destroy', post_path(@post.slug), method: :delete, data: { confirm: 'Are you sure?' }
      |

app/views/posts/edit.html.haml
- if @post.blank?
  Post does not exist or was removed
  %br
- else
  %h1 Editing post
  = form_for @post, url: post_path(@post.slug), method: :put do |f|
    = render 'form', f: f
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h2
  Posts [
  = link_to @posts.count, posts_path
  - if current_user
    = link_to '+', new_user_post_path(user_pseudonym: current_user.pseudonym)
  - else
    +
  - if @posts_archive.count.positive?
    = link_to @posts_archive.count, posts_path(archive: 1)
  - else
    0
  ]
- collection = params[:archive].present? ? @posts_archive : @posts
- index = (collection.current_page - 1) * collection.default_per_page
- if collection.present?
  %table
    %thead
      %tr
        %th= collection.current_page
        %th $
        %th Title
        %th Company
        %th Author
        %th Access
    %tbody
      - collection.each do |post|
        - item = post.slug
        %tr
          %td= index += 1
          %td= link_to item, post_path(item)
          %td= post.title
          %td= company_by_id(post.company_id).present? ? company_by_id(post.company_id).title : '-'
          %td= user_by_id(post.user_id).present? ? user_by_id(post.user_id).name : 'removed'
          %td
            - if post.deleted_at.present?
              nobody
            - else
              = post.keyword.present? ? 'keyword / company' : 'everyone'
  - if params[:archive].present?
    = paginate @posts_archive
  - else
    = paginate @posts
- else
  Nothing so far...

app/views/posts/new.html.haml
%h1
  New post by
  #{current_user.pseudonym}@#{company_by_id(current_user.company_id).title}
= form_for @post do |f|
  = render 'form', f: f
= link_to 'Back', posts_path

app/views/posts/show.html.haml
- if @post.blank?
  Post does not exist or was removed
  %br
- else
  = render 'post'
= link_to 'Back', posts_path