config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, param: :tag do
    resources :users, only: %i[index new create], controller: 'users'
    resources :posts, only: [:index], controller: 'posts'
  end

  resources :users, param: :pseudonym do
    resources :posts, controller: 'posts'
  end

  resources :posts, param: :slug

  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'sign_up' => 'users#new', as: 'sign_up'

  resources :sessions

  root 'posts#index'
end

app/views/layouts/_navbar.html.haml
%nav.current_user
  #user_nav
    - if current_user
      = link_to current_user.pseudonym, user_path(current_user.pseudonym)
      @
      = link_to company_by_id(current_user.company_id).title, company_path(company_by_id(current_user.company_id).tag)
      |
      = link_to 'Log out', log_out_path
    - else
      = link_to 'Sign up', sign_up_path
      or
      = link_to 'Log in', log_in_path
%hr
%h3
  = link_to 'Posts', posts_path
  \/
  = link_to 'Companies', companies_path
  - if current_user
    \/
    = link_to 'Users', users_path

%p#notice= notice
%hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Cms
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render '/layouts/navbar'
    = yield